# workflow to update wiki

name: wiki-update

on:
  push:
    branches: [ master ]  

jobs:
  wiki-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Additional steps to generate documentation in "Documentation" directory
      - name: Upload docs to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
